### ISSUE TITLE
Variadic I/Os Sample Might Be Wrong

### ISSUE THREAD

**Issue by David-Melo** [Gregwar/blocks.js#39]
It reads: 

{
            name: "User #",
            dimension: "n",
            attrs: "output"
 }

shouldn't that be 

{
            name: "User",
            label: "User #",
            dimension: "n",
            attrs: "output"
}

The '#' in the name field causes problems since that ends up in the connectorID and other parts that use the name field

**Comment by Gregwar** [comment]
This is fixed, thanks
If you are looking for examples, you can also have a look to this one:
https://github.com/Gregwar/ArduiFlow

This is an example of tool to program arduino boards using blocks.js

**Comment by David-Melo** [comment]
Thanks for the other example. That really helps. I'm trying to understand this library since I'm hoping to use it on an upcoming project. What you have done is very good and I'm thankful I found it. Great Work.
