### ISSUE TITLE
Allow circular connections

### ISSUE THREAD

**Issue by garagenisse** [Gregwar/blocks.js#41]
As i understand it is not possible to have circular connections, would it be possible to allow this somehow?

**Comment by Gregwar** [comment]
Hello
Actually, this is possible, you can find a solution of this in ArduiFlow:
https://github.com/Gregwar/ArduiFlow
http://gregwar.com/arduiflow/

The idea is that you have a specific block to create the loop, because the data need to be stored one "tick" to be back propagated

**Comment by garagenisse** [comment]
Ah, great, will have a look!
